### ISSUE TITLE
Number of rooms

### ISSUE THREAD

**Issue by VHaftka** [scg-unibe-ch/ese2016-team6#1] opened 2016-10-14 11:24 UTC
Customer can choose the number of rooms he want to search after

**Comment by PIndermuehle** [comment] 2016-10-18 12:09
I got a problem with the search form interface. 
I could not update the interface to properly display an input form for the number of Rooms. I suspect there is an error within SearchAd.jsp
I made a new Branch with the project containing this error. This makes sure the master branch version stays "working as intended".

**Comment by PIndermuehle** [comment] 2016-10-24 12:09
Error is now fixed.

Feature is now implemented
You can now specify the amount of rooms your property has, you can search for properties with a minimum amount of rooms as well.

**Closed** 2016-10-24 12:10 UTC

**Comment by mgpiegette** [comment] 2016-11-02 14:54
#11
